import type {
  AlphaHypothesis,
  EdgeMemoryNode,
} from "@/lib/alpha/types";
import {
  evaluateAlphaHypothesis,
  findEdgeMemoryMatches,
} from "@/lib/alpha/engine";

export const sandboxEdgeMemory: EdgeMemoryNode[] = [
  {
    id: "mem-football-late-lowtempo-total",
    sport: "football",
    marketFamily: "total_goals",
    stateTags: [
      "late-game",
      "draw-state",
      "low-tempo",
      "goal-hazard-down",
      "market-lag",
    ],
    sampleSize: 1180,
    oosWindows: 8,
    meanNetClv: 0.016,
    positiveClvWindowRate: 0.75,
    signalSurvivalRate: 0.67,
    calibrationGain: 0.007,
    regimeStability: 0.79,
    fdrQValue: 0.034,
    executableCoverage: 0.72,
  },
  {
    id: "mem-football-team-total-propagation",
    sport: "football",
    marketFamily: "team_total",
    stateTags: [
      "late-game",
      "low-tempo",
      "goal-hazard-down",
      "team-total-lag",
      "market-lag",
    ],
    sampleSize: 910,
    oosWindows: 7,
    meanNetClv: 0.013,
    positiveClvWindowRate: 0.71,
    signalSurvivalRate: 0.62,
    calibrationGain: 0.005,
    regimeStability: 0.74,
    fdrQValue: 0.047,
    executableCoverage: 0.68,
  },
  {
    id: "mem-football-redcard-tail",
    sport: "football",
    marketFamily: "total_goals",
    stateTags: [
      "red-card",
      "high-volatility",
      "tail-state",
      "late-game",
    ],
    sampleSize: 430,
    oosWindows: 5,
    meanNetClv: 0.006,
    positiveClvWindowRate: 0.6,
    signalSurvivalRate: 0.48,
    calibrationGain: 0.002,
    regimeStability: 0.49,
    fdrQValue: 0.12,
    executableCoverage: 0.51,
  },
  {
    id: "mem-football-main-1x2",
    sport: "football",
    marketFamily: "1x2",
    stateTags: [
      "late-game",
      "draw-state",
      "market-efficient",
      "main-line",
    ],
    sampleSize: 2400,
    oosWindows: 10,
    meanNetClv: 0.003,
    positiveClvWindowRate: 0.5,
    signalSurvivalRate: 0.82,
    calibrationGain: 0.003,
    regimeStability: 0.9,
    fdrQValue: 0.061,
    executableCoverage: 0.9,
  },
  {
    id: "mem-football-fast-shock",
    sport: "football",
    marketFamily: "total_goals",
    stateTags: [
      "information-shock",
      "fast-market",
      "high-latency-risk",
      "goal-hazard-shock",
    ],
    sampleSize: 760,
    oosWindows: 6,
    meanNetClv: 0.009,
    positiveClvWindowRate: 0.67,
    signalSurvivalRate: 0.41,
    calibrationGain: 0.004,
    regimeStability: 0.66,
    fdrQValue: 0.072,
    executableCoverage: 0.47,
  },
];

export const sandboxCurrentAlphaState = {
  sport: "football",
  marketFamily: "total_goals",
  stateTags: [
    "late-game",
    "draw-state",
    "low-tempo",
    "goal-hazard-down",
    "market-lag",
    "team-total-lag",
  ],
};

export const sandboxAlphaHypothesis: AlphaHypothesis = {
  id: "hyp-late-lowtempo-propagation-v1",
  title: "Late low-tempo state + linked-market propagation lag",
  sport: "football",
  marketFamily: "total_goals",
  stateTags: sandboxCurrentAlphaState.stateTags,
  registeredVariants: 12,
  sampleSize: 940,
  oosWindows: 7,
  positiveClvWindows: 5,
  meanNetClv: 0.014,
  calibrationGain: 0.0056,
  logLossGain: 0.0048,
  fdrQValue: 0.043,
  regimeStability: 0.76,
  executableSurvivalRate: 0.63,
  leakageFlags: 0,
};

export const sandboxAlphaMemoryAnalysis = {
  current: sandboxCurrentAlphaState,
  matches: findEdgeMemoryMatches({
    ...sandboxCurrentAlphaState,
    memory: sandboxEdgeMemory,
    limit: 4,
  }),
  hypothesis: sandboxAlphaHypothesis,
  gate: evaluateAlphaHypothesis(sandboxAlphaHypothesis),
};
